import { StyleSheet, Dimensions } from "react-native";

const { width } = Dimensions.get("window");



export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F9FAFB",
  },
  header: {
    paddingTop: 48,
    paddingBottom: 16,
    paddingHorizontal: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  cardContainer: {
    backgroundColor: "#fff",
    borderRadius: 24,
  },
  headerLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  logo: {
    width: 32,
    height: 32,
    backgroundColor: "#22C55E",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  logoText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#22C55E",
  },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    flex: 1,
    paddingHorizontal: 24,
  },
  screen: {
    paddingBottom: 100,
  },

  // ---------- CAMERA ----------
  cameraContainer: {
    flex: 1,
  },
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    flex: 1,
    backgroundColor: "transparent",
  },
  cameraTopBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 48,
    paddingHorizontal: 24,
    paddingBottom: 16,
  },
  cameraBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(0,0,0,0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  cameraTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#fff",
  },
  cameraGuide: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  guideBox: {
    width: 280,
    height: 280,
    position: "relative",
  },
  guideCorner: {
    position: "absolute",
    width: 40,
    height: 40,
    borderColor: "#22C55E",
  },
  guideTopLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 4,
    borderLeftWidth: 4,
    borderTopLeftRadius: 8,
  },
  guideTopRight: {
    top: 0,
    right: 0,
    borderTopWidth: 4,
    borderRightWidth: 4,
    borderTopRightRadius: 8,
  },
  guideBottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderBottomLeftRadius: 8,
  },
  guideBottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 4,
    borderRightWidth: 4,
    borderBottomRightRadius: 8,
  },
  guideText: {
    marginTop: 24,
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
    textAlign: "center",
    backgroundColor: "rgba(0,0,0,0.5)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
  },
  cameraBottomBar: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 48,
    paddingHorizontal: 24,
  },
  captureButton: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "rgba(255,255,255,0.3)",
    borderWidth: 4,
    borderColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  captureButtonInner: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#fff",
  },
  cameraLoading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  cameraPermission: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  permissionTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginTop: 24,
    marginBottom: 12,
    textAlign: "center",
  },
  permissionText: {
    fontSize: 16,
    color: "#6B7280",
    textAlign: "center",
    lineHeight: 24,
    marginBottom: 32,
  },
  permissionButton: {
    backgroundColor: "#22C55E",
    paddingHorizontal: 32,
    paddingVertical: 16,
    borderRadius: 12,
    marginBottom: 12,
  },
  permissionButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "bold",
  },
  permissionBackButton: {
    paddingVertical: 12,
  },
  permissionBackText: {
    color: "#22C55E",
    fontSize: 16,
    fontWeight: "600",
  },

  // ---------- HOME ----------
  welcomeSection: {
    paddingVertical: 8,
  },
  welcomeTitle: {
    fontSize: 30,
    fontWeight: "bold",
    color: "#000",
    lineHeight: 40,
  },
  welcomeTitleGreen: {
    color: "#22C55E",
  },
  welcomeSubtitle: {
    color: "#6B7280",
    marginTop: 8,
    fontSize: 14,
  },
  ctaCard: {
    height: 192,
    backgroundColor: "#22C55E",
    borderRadius: 24,
    padding: 24,
    marginTop: 24,
    overflow: "hidden",
    position: "relative",
  },
  ctaContent: {
    zIndex: 10,
  },
  ctaTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
  },
  ctaSubtitle: {
    color: "rgba(255,255,255,0.9)",
    fontSize: 14,
    marginTop: 4,
    maxWidth: "60%",
  },
  ctaButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginTop: 16,
    gap: 8,
  },
  ctaButtonText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  ctaLeaf: {
    position: "absolute",
    right: 8,
    bottom: 8,
    transform: [{ rotate: "12deg" }],
  },
  statsRow: {
    flexDirection: "row",
    gap: 16,
    marginTop: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  statIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
  },
  statNumber: {
    fontSize: 24,
    fontWeight: "bold",
  },
  statLabel: {
    fontSize: 12,
    color: "#6B7280",
  },
  tipsSection: {
    marginTop: 24,
  },
  tipsSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  tipsTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  tipsViewAll: {
    fontSize: 12,
    color: "#22C55E",
    fontWeight: "600",
  },
  tipCard: {
    backgroundColor: "#fff",
    padding: 16,
    borderRadius: 12,
    flexDirection: "row",
    gap: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  tipIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  tipContent: {
    flex: 1,
  },
  tipTitle: {
    fontWeight: "bold",
    fontSize: 14,
    marginBottom: 4,
  },
  tipDesc: {
    fontSize: 12,
    color: "#6B7280",
    lineHeight: 18,
  },

  // ---------- BOTTOM NAV ----------
  bottomNav: {
    position: "absolute",
    bottom: 24,
    left: 24,
    right: 24,
    height: 64,
    backgroundColor: "rgba(255,255,255,0.9)",
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 8,
    shadowColor: "#22C55E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  navButton: {
    padding: 12,
    borderRadius: 12,
  },
  navButtonActive: {
    backgroundColor: "rgba(34,197,94,0.1)",
  },
  fabButton: {
    width: 64,
    height: 64,
    backgroundColor: "#22C55E",
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#22C55E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    marginTop: -32,
  },

  // ---------- UPLOAD ----------
  uploadHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 32,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  uploadTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  uploadContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingBottom: 100,
  },
  uploadIconContainer: {
    width: 96,
    height: 96,
    backgroundColor: "rgba(34,197,94,0.1)",
    borderRadius: 48,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  uploadMainTitle: {
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 8,
  },
  uploadSubtitle: {
    fontSize: 14,
    color: "#6B7280",
    textAlign: "center",
    paddingHorizontal: 32,
    marginBottom: 32,
  },
  uploadButtonPrimary: {
    flexDirection: "row",
    backgroundColor: "#22C55E",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
    gap: 12,
    marginBottom: 12,
    width: width - 48,
  },
  uploadButtonPrimaryText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "bold",
  },
  uploadButtonSecondary: {
    flexDirection: "row",
    backgroundColor: "#fff",
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 16,
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    width: width - 48,
  },
  uploadButtonSecondaryText: {
    color: "#000",
    fontSize: 18,
    fontWeight: "bold",
  },

  // ---------- SCANNING ----------
  scanningContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: 100,
  },
  scanningImageContainer: {
    width: 256,
    height: 256,
    borderRadius: 16,
    overflow: "hidden",
    borderWidth: 4,
    borderColor: "rgba(255,255,255,0.2)",
    backgroundColor: "rgba(0,0,0,0.5)",
    position: "relative",
  },
  scanningImage: {
    width: "100%",
    height: "100%",
  },
  scanLine: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: "#22C55E",
    shadowColor: "#22C55E",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
  },
  scanningText: {
    fontSize: 18,
    fontWeight: "600",
    marginTop: 32,
    color: "#000",
  },
  scanningSubtext: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 8,
  },

  // ---------- RESULTS ----------
  resultsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  resultsTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  resultCard: {
    backgroundColor: "#fff",
    borderRadius: 24,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 24,
  },
  resultCardHeader: {
    height: 160,
    backgroundColor: "#FFF7ED",
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  confidenceBadge: {
    position: "absolute",
    bottom: 16,
    right: 16,
    backgroundColor: "rgba(255,255,255,0.8)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#FED7AA",
  },
  confidenceText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#F97316",
  },
  resultCardContent: {
    padding: 24,
  },
  resultCardTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  resultDisease: {
    fontSize: 24,
    fontWeight: "bold",
  },
  resultScientific: {
    fontSize: 14,
    color: "#6B7280",
  },
  criticalBadge: {
    backgroundColor: "#FEE2E2",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
  },
  criticalText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#DC2626",
  },
  resultDescription: {
    fontSize: 14,
    color: "#6B7280",
    marginTop: 16,
    lineHeight: 20,
  },
  recommendationsTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 16,
  },
  treatmentCard: {
    flexDirection: "row",
    gap: 16,
    padding: 16,
    backgroundColor: "#fff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(229,231,235,0.5)",
    marginBottom: 12,
  },
  treatmentStep: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(34,197,94,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  treatmentStepText: {
    color: "#22C55E",
    fontWeight: "bold",
    fontSize: 14,
  },
  treatmentContent: {
    flex: 1,
  },
  treatmentTitle: {
    fontWeight: "bold",
    fontSize: 14,
    marginBottom: 4,
  },
  treatmentDesc: {
    fontSize: 12,
    color: "#6B7280",
  },
  actionButtons: {
    flexDirection: "row",
    gap: 12,
    marginTop: 24,
  },
  actionButtonSecondary: {
    flex: 1,
    backgroundColor: "#F3F4F6",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
  },
  actionButtonSecondaryText: {
    fontWeight: "bold",
    fontSize: 16,
  },
  actionButtonPrimary: {
    flex: 1,
    backgroundColor: "#22C55E",
    paddingVertical: 16,
    borderRadius: 16,
    alignItems: "center",
    shadowColor: "#22C55E",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 4,
  },
  actionButtonPrimaryText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },

  // ---------- ABOUT/Profile ----------
  aboutHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  aboutTitle: {
    fontSize: 18,
    fontWeight: "bold",
  },
  profileCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    padding: 16,
    backgroundColor: "#fff",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    marginBottom: 24,
  },
  profileAvatar: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "#D1FAE5",
    alignItems: "center",
    justifyContent: "center",
  },
  profileEmoji: {
    fontSize: 32,
  },
  profileName: {
    fontSize: 18,
    fontWeight: "bold",
  },
  profileMembership: {
    fontSize: 14,
    color: "#6B7280",
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#6B7280",
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 16,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "transparent",
    borderRadius: 12,
    marginBottom: 4,
  },
  menuItemLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  menuItemLabel: {
    fontSize: 16,
    fontWeight: "500",
  },
  footer: {
    marginTop: 32,
    alignItems: "center",
  },
  footerBrand: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  footerBrandText: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#22C55E",
  },
  footerVersion: {
    fontSize: 12,
    color: "#6B7280",
  },
});
